meta:
  engine: 4.1.0
  author: Diablica
  name: legendary-guacamole
units:
  kx: U
  ky: U

  px: 2
  py: 2

  # dont forget that choc v2 is essentially mx
  plate_thickness: 1.5 # choc: 1.2, mx: 1.5
  kcox: 14 # key cutout (choc: 13.8, mx: 14)
  kcoy: 14 # key cutout (choc: 13.8, mx: 14)
points:
  zones:
    matrix:
      anchor:
        shift: [100,100]
      columns:
        outer:
          rows.top.skip: true
        pinky:
        ring:
          key.stagger: u/3
        middle:
          key.stagger: u/3
        index:
          key.stagger: -u/3
        inner:
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-14, -(7/3)u]
      columns:
        thumb_1:
        thumb_2:
          key.origin: [0, -9]
          key.splay: -10
        thumb_3:
          key.height: 2ky
          key.origin: [-9.5, -9]
          key.shift: [0,U/2]
          rows.row_1.skip: true
          key.splay: -10
      rows:
        row_0:
        row_1:

outlines:
pcbs:
  legendaryGuacamole_pcb:
    footprints:
      mx:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          BAT_P: BAT_P
          BAT_N: GND
          reversible: true
          include_courtyard: false
        where:
          ref: matrix_inner_home
          shift: [0, 0.75ky]
          rotate: -90

cases: