meta:
  engine: 4.1.0
  author: Diablica
  name: legendary-guacamole
units:
  kx: U
  ky: U

  px: 2
  py: 2

  # dont forget that choc v2 is essentially mx
  plate_thickness: 1.5 # choc: 1.2, mx: 1.5
  kcox: 14 # key cutout (choc: 13.8, mx: 14)
  kcoy: 14 # key cutout (choc: 13.8, mx: 14)
points:
  zones:
    matrix:
      columns:
        outer:
          rows.top.skip: true
        pinky:
        ring:
          key.stagger: u/3
        middle:
          key.stagger: u/3
        index:
          key.stagger: -u/3
        inner:
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-u/2,-(4/3)u]
      columns:
        thumb_1:
        thumb_2:
          key:
            rotate: -15
            stagger: -1
            spread: 25
        thumb_3:
          key:
            rotate: -25
            stagger: -8 
            spread: 23
        thumb_4:
          key:
            height: 2ky
            rotate: -25
            stagger: -18 
            spread: 15
      rows:
        row_1:

          

outlines:
pcbs:
cases:
